### ISSUE TITLE
IndicatorWeight error with example from Vignette

### ISSUE THREAD

**Issue by cgpu** [guokai8/VennDetail#1]
Hi and thank you for the very nice visualisation in VennDetail,

I am trying to reproduce the venn diagram from the vignette and I get this error:

## Code
```r
devtools::install_github("guokai8/VennDetail")
library(VennDetail)
data(T2DM)
ven <- venndetail(list(Cortex = T2DM$Cortex$Entrez, SCN = T2DM$SCN$Entrez,Glom = T2DM$Glom$Entrez) )
plot(ven)
```

## Error message
```r
Error in ncol(object@IndicatorWeight) : 
  no slot of name "IndicatorWeight" for this object of class "Venn"
```

Could you point me to what I should check? 

Thanks in advance

**Comment by guokai8** [comment]
Hi @cgpu,
I tried to reinstall the package and run the commands you posted however I can't reproduced the issue here. Could you please try 1) use sessionInfo() to show the details for your R environment;
2) reinstall the package with the BiocManager since the package was already included in the bioconductor. 
Thanks!

**Comment by cgpu** [comment]
Hi @guokai8,

Thanks for the prompt response.

I checked in the package's codebase and this is not exported from `VennDetail`, but another venn R package I was testing (`Vennerable`), that was loaded in namespace.

Apologies for a false issue on my side.
I tried on a fresh rstudio session and it worked as expected.

Feel free to close the issue.

Thanks!
